name: React CI/CD

on:
  push:
    branches:
      - master

jobs:
  build-react-server:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - name: Checking out code
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Install dependencies
        run: npm ci --no-optional --ignore-scripts

      - name: Build project
        env:
          NODE_ENV: production
        run: npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      - name: Debugging
        run: |
             pwd  # Print current working directory
              ls   # List contents of the current directory
  

      - name: Deploy to S3 bucket
        run: |
         aws s3 sync ./dist/ s3://nodejs123 --delete

